export interface User {
    email: string,
    fullName?: string,
    age?: number,
    height?: number,
    weight?: number,
    apeIndex?: number,
    gradingPreference: boolean,
    measurementSystem: boolean,
}

export interface Session {
    id: number,
    userId: string,
    intensity: number,
    notes?: string,
    createdAt: Date,
}

export interface Climb {
    id: number,
    name: string,
    sessionId: number,
    type: ClimbTypeEnum,
    style: ClimbStyleEnum,
    grade: string,
    attempts: number,
}

export enum ClimbTypeEnum {
    TOP_ROPE = 'Top Rope',
    LEAD = 'Lead',
    BOULDER = 'Boulder',
}

export enum ClimbStyleEnum {
    SLAB = 'Slab',
    VERTICAL = 'Verical',
    OVERHANG = 'Overhang',
    CAVE = 'Cave',
}

export const boulderGradeMapping: Record<string, string> = {
    "VB": "3",
    "V0-": "4-",
    "V0": "4",
    "V0+": "4+",
    "V1": "5",
    "V2": "5+",
    "V3": "6a",
    "V3+": "6a+",
    "V4": "6b",
    "V4+": "6b+",
    "V5": "6c",
    "V5+": "6c+",
    "V6": "7a",
    "V6+": "7a+",
    "V7": "7b",
    "V7+": "7b+",
    "V8": "7c",
    "V8+": "7c+",
    "V9": "8a",
    "V10": "8a+",
    "V11": "8b",
    "V12": "8b+",
    "V13": "8c",
    "V13+": "8c+",
    "V14": "8c+/9a",
    "V15": "9a",
    "V16": "9a+",
    "V17": "9b",
};

export const routeGradeMapping: Record<string, string> = {
    "5.0": "2-",
    "5.1": "2",
    "5.2": "3",
    "5.3": "3+",
    "5.4": "4a",
    "5.5": "4b",
    "5.6": "4c",
    "5.7": "5a",
    "5.8": "5b",
    "5.9": "5c",
    "5.10a": "6a",
    "5.10b": "6a+",
    "5.10c": "6b",
    "5.10d": "6b+",
    "5.11a": "6c",
    "5.11b": "6c+",
    "5.11c": "6c+",
    "5.11d": "7a",
    "5.12a": "7a+",
    "5.12b": "7b",
    "5.12c": "7b+",
    "5.12d": "7c",
    "5.13a": "7c+",
    "5.13b": "8a",
    "5.13c": "8a+",
    "5.13d": "8b",
    "5.14a": "8b+",
    "5.14b": "8c",
    "5.14c": "8c+",
    "5.14d": "9a",
    "5.15a": "9a+",
    "5.15b": "9b",
    "5.15c": "9b+",
    "5.15d": "9c",
}